salesforcecli/plugin-data

README.md, package.json, packages/plugin-data/README.md, yarn.lock
=> chore: update readme

packages/plugin-data/test/commands/force/data/tree/export.test.ts, packages/plugin-data/test/commands/force/data/tree/import.test.ts
=> stub writing the data file and correct some test descriptions

packages/data/package.json, packages/plugin-data/package.json
=> chore: reconcile version numbers

packages/data/tsconfig.json, packages/plugin-data/tsconfig.json
This PR prettify the contents of the tsconfig.json of each package, right now the json doesn't work as expected by the JSON.parse command that why we need it to be cleaned
W-9024415
=> chore: prettify tsconfig json

packages/plugin-data/messages/bulk.delete.json, packages/plugin-data/messages/bulk.status.json, packages/plugin-data/messages/bulk.upsert.json, packages/plugin-data/messages/soql.query.json
@W-9055353@ add message parts that were dropped in data plugin migration.
Restores help parts dropped during data plugin migration.
@W-9055353@
=> fix: correct help for data commands

packages/plugin-data/package.json
Updates the scripts to work nicely with lerna
=> chore: update scripts

packages/plugin-data/package.json
Add "@oclif/dev-cli" dep
@W-8969970@
=> fix: add oclif/dev dependency [skip-validate-pr]

packages/plugin-data/package.json
=> chore: depend on 0.1.5

packages/data/package.json, packages/plugin-data/package.json, yarn.lock
removes unused kit dependency, latest version of core
https://app.circleci.com/pipelines/github/salesforcecli/sfdx-cli/653/workflows/2235f3b6-bfe3-45ac-883d-69d4ab0f60f5/jobs/3145
@W-0@
=> fix: dependency pruning

.circleci/config.yml
sets up the dependabot automerge to run
@W-8776229@
=> chore: dependabot jobs

package.json, yarn.lock
Bumps core and jsforce types
@W-9805905@
=> chore: bump core and jsforce types

package.json, yarn.lock
Fixes type error in core
Failing builds
https://github.com/forcedotcom/sfdx-core/pull/536
https://github.com/forcedotcom/sfdx-core/pull/535
Previous issue
https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1643067299196700
https://github.com/salesforcecli/plugin-data/pull/265
[@W-10745422@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10745422)
=> fix: bump core and jsforce types versions

messages/bulk.delete.json, messages/bulk.status.json, messages/bulk.upsert.json, messages/record.create.json, messages/record.delete.json, messages/record.get.json, messages/record.update.json, messages/soql.query.json, messages/tree.export.json, messages/tree.import.json
Adds a prompt to examples so they're tagged correctly in CLI Ref generation.
@W-11164018@
=> Add prompt to examples

src/reporters.ts
Guards against reflect.ownKeys being called on an undefined object
@W-12024471@
=> fix: own keys on a undefined object

command-snapshot.json, messages/bulk.delete.md, messages/bulk.delete.resume.md, messages/bulk.resume.command.md, messages/bulk.status.md, messages/bulk.upsert.md, messages/bulk.upsert.resume.md, messages/bulkv2.delete.md, messages/bulkv2.upsert.md, messages/messages.md, messages/soql.query.md, src/commands/data/delete/bulk.ts, src/commands/data/query/resume.ts, src/commands/data/resume.ts, src/commands/data/upsert/bulk.ts, src/flags.ts, src/resumeBulkCommand.ts
Cleans up messages after Pete's addition of --use-most-recent to some bulk data commands
@W-12083162@
=> fix: clean up messages after pete's change to resume

package.json, yarn.lock
bump testkit, etc
to fix failure like https://github.com/salesforcecli/sf-plugins-core/actions/runs/4304149479/jobs/7504783947
=> chore: bump deps, esp testkit

package.json
Updates topic desc in package.json for correct --help and CLI Command Ref
@W-12565029@
=> fix: update package.json for correct command ref

package.json, yarn.lock
=> fix: bump and dedup ts-types

messages/bulkv2.upsert.md
=> fix: ** to __

src/commands/data/query.ts
last PR forgot to hook the flag up to the bulk query 
forcedotcom/cli#1959
@W-12590109@
=> fix: actually pass the all-rows flag to the bulk api query

test/commands/data/dataSoqlQuery.nut.ts, test/commands/data/query/resume.nut.ts, test/commands/data/record/dataRecord.nut.ts, test/commands/data/tree/dataTree.nut.ts, test/commands/force/data/bulk/dataBulk.nut.ts
remove sfdx references
@W-12607169@
=> test: remove sfdx references from NUTs

messages/tree.export.md
small messages update
@W-13907820@
=> fix: small messages update

package.json, yarn.lock
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/7214346950/job/19656240784
=> fix(deps): missing dependency

messages/tree.export.md
Fix inadvertent replacement of `Address__c `with `Address\_\_c` in messages file. 
@W-@
=> fix: Fix double-underscore annoyance.

messages/tree.export.md
Fixes the example in which Address__c got switched to Address**c
@W-16162909@
=> fix: example switched to "**" instead of "__"

messages/soql.query.md
Adds "sf" in front of suggested command in error message so users can copy-and-paste.
@W-16314196@
=> fix: update try this message so users can copy-and-paste

src/commands/data/import/tree.ts
use comma-delimited array
https://github.com/salesforcecli/sf-plugins-core/actions/runs/10118076316/job/27984302448?pr=598#step:12:9
=> fix: use native string array

messages/data.export.bulk.md, messages/data.export.resume.md
Edits messages for two new data bulk commands
@W-16925836@
=> edit messages for two new "data bulk" commands

messages/data.import.bulk.md, messages/data.import.resume.md
Edit messages for new "data import bulk|resume" commands
@W-16992840@
=> Edit messages for new "data import bulk|resume" commands

package.json
=> test: add back nuts

.github/workflows/onRelease.yml, .github/workflows/test.yml, messages/batcher.md, package.json, src/batcher.ts, test/commands/batcher.test.ts, test/commands/data/tree/dataTreeMoreThan200.nut.ts, test/commands/force/data/bulk/dataBulk.nut.ts, yarn.lock
Fixes `sf force data bulk upsert` leaving unresolved promises when upserting +10K records and waiting for it to complete (`--wait <min>`).
The bug only occurs under the following conditions:
* upserting +10K records (the bug happens when waiting for multiple batches to finish)
* synchronous operation (`--wait <min>`)
You can even modify the batcher limit to something lower like 1K and upsert a 2K records csv to repro:
https://github.com/salesforcecli/plugin-data/blob/6f1445be09e847ab6197cc7fbdb095a6e3c79f69/src/batcher.ts#L23
`batchesCompleted`'s initial value from the caller is `0` here:
https://github.com/salesforcecli/plugin-data/blob/6f1445be09e847ab6197cc7fbdb095a6e3c79f69/src/batcher.ts#L261
but `waitForCompletion` is called once per batch so its value on each call was always 0 …
=> fix(bulk-v1): properly handle +1 job batches
