packages/plugin-data/messages/record.get.json
packages/plugin-data/src/commands/force/data/record/create.ts
packages/plugin-data/src/commands/force/data/record/get.ts
packages/plugin-data/src/dataCommand.ts
packages/plugin-data/test/commands/force/data/record/get.test.ts

Fixes the following:
- Missing description for `force:data:record:get`
- Show expected error message when `force:data:record:get --where` returns multiple records
- Make human readable output for `force:data:record:get` consistent with output from the toolbelt version
@W-8449664@

fix: various data:record bugs

---

packages/plugin-data/src/batcher.ts
packages/plugin-data/src/commands/force/data/bulk/delete.ts
packages/plugin-data/src/commands/force/data/bulk/upsert.ts

passes csv to utf-8 encoding, and then adds the bom parsing option to the parser, which is now safe because the files are utf-8 encoded.
@W-8836961@
https://github.com/forcedotcom/cli/issues/720

fix: parse csv as utf-8 and enable bom parsing

---

packages/plugin-data/src/dataCommand.ts

fix casing to honor the flag `usetoolingapi`
@W-8879900@

fix: commands ignore --usetoolingapi

---

.github/autointegrator.yml
package.json

Removes `codecov` command from `package.json`
It also remove `autointegrator.yml` from `.github` directory
@W-9228425@

chore: remove codecov command

---

packages/plugin-data/command-snapshot.json
packages/plugin-data/messages/bulk.upsert.json
packages/plugin-data/src/commands/force/data/bulk/upsert.ts
packages/plugin-data/test/commands/force/data/bulk/dataBulk.nut.ts
packages/plugin-data/test/commands/force/data/bulk/upsert.test.ts

Added a new boolean flag --serial for the "force:data:bulk:upsert" command,  which will allow the job to run serially. 
Github Issue Link : https://github.com/forcedotcom/cli/issues/882
@W-8934566@

feat: added new flag for serial process

---

src/commands/force/data/soql/query.ts
test/commands/force/data/soql/query/dataSoqlQuery.nut.ts

Adds a failing NUT to show the fix working
will fix the `[object Object]` in the following commits
@W-9881177@
https://github.com/forcedotcom/cli/issues/1164

chore: failing NUT

---

package.json
yarn.lock

downgrades the eslint-plugin-jsdoc dev-dependency so that NodeJS 17 can be used.  Once that lib publishes a version that supports node 17 we can update it.
@W-0@

fix: downgrade eslint jsdoc dep

---

package.json
src/batcher.ts
test/commands/batcher.test.ts
yarn.lock

Enables splitting files at the 10M character line and not just the 10K row line.
Also added a fix and test so we don't create empty batches if we have exactly 10K rows of input.
https://github.com/forcedotcom/cli/issues/1460

fix: bulk batching wide fIles (cli/#1460)

---

schema/dataImportPlanSchema.json

Updates the schema to support JSON Schema Draft 7 which is used in AJV. See https://github.com/forcedotcom/sfdx-core/pull/569
This can be merged at any point and does not need to wait for core changes.
These changes do not affect the current JSEN Draft 4 validation. 
(Additional reassurance: The schemas at https://github.com/forcedotcom/schemas are already declaring Draft 7 despite JSEN using Draft 4)
- Pull this branch
- Run unit and NU[T] tests (all pass)
- Pull https://github.com/forcedotcom/sfdx-core/pull/569
- `yarn link @salesforce/core`
- Run unit and NU[T] tests again (all pass)
[@W-10818834@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10818834)

Update schema to support AJV

---

bin/dev
bin/dev.cmd
package.json
src/commands/force/data/soql/query.ts
test/commands/force/data/soql/query/dataSoqlQuery.nut.ts
test/soqlQuery.test.ts
yarn.lock

Makes `SoqlQuery` wait until all records are emitted from jsforce, also it accepts a config aggregator as a parameter(no default, the caller should pass `this.configAggregator` or create a new instance.
others:
added 2 NUTs for maxQueryLimit
reverted default limit back to 50000
@W-11204187@
https://github.com/forcedotcom/cli/issues/1543

fix: wait until all records are emitted

---

command-snapshot.json
messages/soql.query.json
src/commands/force/data/soql/query.ts
test/commands/force/data/bulk/status.test.ts
test/commands/force/data/soql/query/dataSoqlQuery.nut.ts
test/commands/force/data/soql/query/dataSoqlQueryCommand.test.ts

adds a `--soqlqueryfile` flag to contain larger SOQL queries
exclusive to `--query`
@W-9036554@
https://github.com/forcedotcom/cli/issues/360

feat: add a soqlqueryfile parameter to allow longer queries

---

test/commands/force/data/dataCommand.test.ts

Adds unit tests for the `dataCommand.stringToDictionary()` method. This is so that we can then compare the changes in https://github.com/salesforcecli/plugin-data/pull/427/files to the existing behavior of the method.
@W-12105706@

chore: add some unit tests for dataCommand class

---

src/dataCommand.ts
test/commands/force/data/dataCommand.test.ts
test/commands/force/data/record/get.test.ts

Allows using `'` in the value  of name-value pairs for flags such as `force:data:record:create`'s `--values`.
https://github.com/forcedotcom/cli/issues/1820
@W-12105706@

fix: allow single quotes in key=value pairs

---

src/BulkBaseCommand.ts

when any batch/record fails in the bulk api transaction, set the exitcode to 1
https://github.com/forcedotcom/cli/issues/1648
@W-11509580@
QA:
create a project
create an org
Make a "bad" csv like this 
```csv
Id
0000sdfsdfsdf
```
`../bin/dev data:delete:bulk --sobject Account --file ../foo.csv --wait 50`

fix: exit 1 when any batch/record fails

---

command-snapshot.json
messages/bulk.operation.command.md
package.json
src/bulkOperationCommand.ts
src/commands/data/delete/bulk.ts
src/commands/data/upsert/bulk.ts
test/commands/data/dataBulk.nut.ts

This adds a `--verbose` flag to the `sf data delete bulk` and `sf data upsert bulk` commands. If set, failed records will be printed as table:
https://github.com/forcedotcom/cli/issues/2221
* How to write tests for this? I tried to mock the `node-fetch` library which is used by `BulkApiV2.request` but this is quite hard to accomplish. Maybe someone has some other ideas?
* Currently we skip the table printing if `--json` is set. This is because otherwise the printed JSON would be malformed.
* How to deal with the returned `Id` column? The only thing we know for sure is that SF will give us the `sf__Id` column. But if an error occures (for example when trying to delete records) this column won't be filled and it might make more sense to have the actual source `Id` column (or external id in …

feat: add verbose flag to bulk delete and upsert

---

messages/messages.md
src/flags.ts

Assert `target-org` flag type so that `@oclif/core@v3` won't think that it's possibly undefined. 
Using the spread operator to extend flags is an anti-pattern and should be avoided. The types in v3 are more accurate which means we can no longer get away with anti-patterns like this. If we have to do this sort of thing the better approach would be to expose the defaults for the custom flag so that they can be reused.
So instead of this,
```typescript
// @salesforce/sf-plugins-core
export const requiredHubFlagWithDeprecations = requiredHubFlag({
aliases: ['targetdevhubusername'],
deprecateAliases: true,
required: true,
});
```
```typescript
// @salesforce/plugin-data
'target-org': {...requiredHubFlagWithDeprecations, summary: 'a summary'}
```
You would do this,
```typescript
// …
```

fix: assert flag type

---

messages/tree.export.md

Changes "**" back to "__" in the examples
@ W-14203132@

fix: change "**" back to "__" in example

---

messages/bulk.operation.command.md
messages/record.update.md

Some help for bulk update/upsert commands mention deleting, so I either changed the word, or in the case where the same flag summary was being used for two commands, I change "delete" to "update or delete". 
@W-14250905@

fix: bulk update/upsert commands mention "delete"

---

messages/tree.import.md
schema/dataImportPlanSchema.json
src/commands/data/import/tree.ts

there is an entire set of classes in sfdx-core that's only used by plugin-data.
what do they do?  print what's now in `messages/tree.import` in an exquisitely complicated process based on the contents of `schema/dataImportPlanSchema.json`
also updated that to not talk about the Sfdx Toolbelt.  😄 
tangentially related to [@W-14085765@](https://gus.lightning.force.com/a07EE00001a9pRDYAY) 
[removing deprecated stuff from sfdx-core because major release because configFile]

fix: static import schema help

---

package.json
src/BulkBaseCommand.ts
src/bulkOperationCommand.ts
src/commands/force/data/bulk/delete.ts
src/commands/force/data/bulk/upsert.ts
src/resumeBulkCommand.ts
yarn.lock

> there's a bug in plugins-core that broke the NUTs. fix: https://github.com/salesforcecli/sf-plugins-core/pull/470
use defaultValue on Duration flags
https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1701888844122029
@W-14625639@
QA:
if you want to link the plugin or use bin/run, you need to run `yarn oclif manfiest` first to get the manifest, which is where you could see the problem before this fix

fix: default wait

---

command-snapshot.json
package.json
src/resumeBulkCommand.ts
yarn.lock

Fix compilation errors when `SfCommand` has `baseFlags`. Can be merged independently of https://github.com/salesforcecli/sf-plugins-core/pull/519
@W-15213828@

fix: spread SfCommand.baseFlags

---

README.md
messages/bulk.resume.command.md
src/commands/data/query/resume.ts
src/resumeBulkCommand.ts

Restores the summary on the `--target-org` flag (`optionalOrgFlagWithDeprecations` from sf-plugins-core doesn't have a summary on it)
@W-15353083@

fix: restore --target-org summary

---

messages/data.create.file.md

Edits messages for the new "data create file" command.
@W-15771775@

fix: edit messages for "data create file"

---

command-snapshot.json
messages/data.create.file.md
package.json
src/api/data/tree/exportApi.ts
src/api/data/tree/importApi.ts
src/api/data/tree/importTypes.ts
src/api/file/fileToContentVersion.ts
src/commands/data/create/file.ts
src/dataSoqlQueryTypes.ts
src/export.ts
test/api/data/tree/exportApi.test.ts
test/commands/data/create/file.nut.ts
test/commands/data/dataSoqlQuery.nut.ts
test/commands/data/record/dataRecord.nut.ts
test/commands/force/data/bulk/dataBulk.nut.ts
yarn.lock

adds a new command to upload files and optionally attach them to records
to replace a 3PP plugin command used by one of the commerce plugins
used `create` because of definition here https://github.com/salesforcecli/cli/wiki/Design-Guidelines-Common-Actions
part of https://github.com/forcedotcom/cli/discussions/2344
related to https://github.com/forcedotcom/cli/discussions/2346

feat: file upload

---

package.json
src/batcher.ts
yarn.lock

use the same major version of csv-parse that jsforce ships with.  [1.2 MB local]
uses the ESM version

fix(deps): next major of csv-parse

---

messages/tree.export.md
messages/tree.import.md
src/commands/data/import/tree.ts

update messages for new GA data import commands
@W-16113657@

update messages for new GA data import commands

---

messages/data.search.md

Embellishes the skeleton `--help` for the new "data search" command.
@W-16448626@

write help for new "data search" command

---

messages/data.search.md
src/commands/data/query.ts
src/commands/data/query/resume.ts
src/commands/data/search.ts
src/flags.ts
src/reporters/search/humanSearchReporter.ts
test/reporters/humanSearchReporter.test.ts

- use oclif's Flags.custom to get a typed option flag that doesn't need ...spread to override the summary
- explicitly disallow `--result-format` with `--json`

refactor: type-fix-for-result-format

---

package.json
src/commands/data/export/bulk.ts
src/commands/data/export/resume.ts
yarn.lock

bump oclif/mso, update calls to `ms.stop` (no longer takes an error).
no function changes, example trying to export records with a bad query:

fix: bump oclif/mso

---

command-snapshot.json
messages/data.import.bulk.md
messages/data.import.resume.md
messages/messages.md
package.json
src/bulkDataRequestCache.ts
src/commands/data/import/bulk.ts
src/commands/data/import/resume.ts
src/types.ts
src/ux/bulkImportStages.ts
test/commands/data/export/bulk.nut.ts
test/commands/data/export/resume.nut.ts
test/commands/data/import/bulk.nut.ts
test/commands/data/import/resume.nut.ts

Adds 2 new commands:
take a CSV with fields of an object and bulk insert them into the org:
https://github.com/user-attachments/assets/aaf214c5-c36b-46e3-aee9-44cbebc4edeb
https://github.com/user-attachments/assets/a8699832-e161-4873-bddc-cc6fd9456bd5
https://github.com/user-attachments/assets/a099d732-6a40-41f3-830e-76af786dfe11
resume an async/timed out import
https://github.com/user-attachments/assets/b05e4849-abb9-4d15-9ee0-983444132f35
checkout PR locally and `sf plugins link` it, you can use the following CSV files available in plugin-data for testing:
`test/test-files/data-project/data/bulkUpsertLarge.csv` (big)
`test/test-files/data-project/data/bulkUpsert.csv` (smol)
@W-13656292@

feat: add `import bulk/resume` commands

---

messages/data.bulk.results.md

edit messages for new command "data bulk results"
@W-17040824@

fix: edit messages for new command "data bulk results"

---

messages/importApi.md
src/api/data/tree/importCommon.ts
src/api/data/tree/importFiles.ts
src/api/data/tree/importPlan.ts
test/api/data/tree/importApi.test.ts
test/api/data/tree/test-files/travel-expense.json

if you export with a similar command `data tree export --query "SELECT RecordType.Name, Name FROM Account`  
`data:tree:import` can now resolve the `RecordType` sub-reference correctly
NUTs weren't possible due to a manual step in the target org 😦 
@W-4472514@

fix: add ability to import RecordTypeId when RecordType.Name is present

---

messages/data.export.resume.md
messages/data.update.bulk.md
messages/data.update.resume.md

Edit help for new "data update bulk|resume" commands
@W-17080794@

Edit help for new "data update bulk|resume" commands

---

command-snapshot.json
messages/reporter.md
messages/soql.query.md
src/commands/data/query.ts
src/queryUtils.ts
src/reporters/query/csvReporter.ts
src/reporters/query/reporters.ts
test/commands/data/query/query.nut.ts

Adds `--output-file` flag to `data query` command.
`data query` has 3 output formats (`csv`, `json` or `human`, can be set via `--result-format`), the new `--output-file` will only work with `csv` and `json` format b/c:
1. those 2 formats are consumable by other tools
2. `human` format uses oclif/table which can't make it write output to a file instead of stdout without some additional work.
expected behavior:
* no `--output-file` -> records printed to stdout
* `--output-file` and `--result-format` csv or json -> records saved to file
* `--output-file` and `--result-format` csv or json and `--json` -> records saved to file, json output includes file path
* `--output-file` and `--result-format human` -> error
See https://salesforce.quip.com/QuS1ABld0leA
@W-17336452@

feat(data:query): add `--output-file` flag

---

src/bulkUtils.ts

Updates bulk export utility to ensure it doesn't check if the JSON file where records will be written already exists.
For a few thousands of records, the API will still return all in one batch so NUTs were passing but if the job splits results in +1 batch then `data export bulk --result-format json` fails when trying to save the second batch because the FS flag instructs node to fail if the file already exists (which does, from the 1st batch that was saved).
repro:
query `ScratchOrgInfo` records in our na40 hub, there are ~1.6M records that get split in ~8 batches:
```
sf data export bulk -q 'select id,ExpirationDate from scratchorginfo' --result-format json --target-org na40 --output-file data.json --wait 20
```
you should get `Error (EEXIST): EEXIST: file already exists, open …

fix(data:export): properly handle big JSON exports

---

src/commands/data/query.ts
src/commands/data/query/resume.ts

Deprecates bulk mode for `data query`, that includes:
* data query flags: `--bulk`, --wait` and `--async`
* `data query resume` command (it only resumes `data query --bulk` operations.
Last bits of the `Enhance and Expand CLI "Bulk Query" Operations` epic, `data export bulk` is better suited to handle million of records.
@W-17396706@

fix(data:query): deprecate bulk mode

---

src/bulkUtils.ts
test/bulkUtils.test.ts
test/test-files/csv/single-column.csv

Updates `detectDelimiter` utility to fallback to `COMMA` if it can't find the delimiter used in a CSV file:
https://github.com/salesforcecli/plugin-data/pull/1110#issuecomment-2545106587
We already do this for `data delete bulk` (the CSV is required to be just 1-column of record IDs):
https://github.com/salesforcecli/plugin-data/blob/1b02e4a60f3944a8e208fa7bf86475815481212a/src/bulkIngest.ts#L74
We set it to `COMMA` in the payload but any valid delimiter works, the API defaults to `COMMA` if not specified anyway:
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/create_job.htm
@W-17443248@

fix(bulk): fallback `columnDelimtier` to `COMMA`

---

src/bulkDataRequestCache.ts
src/bulkIngest.ts
src/commands/data/delete/resume.ts
src/commands/data/upsert/resume.ts
test/commands/data/dataBulk.nut.ts

Removes deprecated functionality for `sf data delete/upsert bulk`:
* Remove record failures from JSON output, should use data bulk results to get failures
* No longer allow resuming sync operations without cache
@W-18057437@

fix: remove deprecations W-18057437

---

src/bulkIngest.ts
src/commands/data/export/bulk.ts
src/commands/data/import/bulk.ts
src/commands/data/query.ts
src/commands/data/update/bulk.ts

Deprecates the --async flag in the following commands:
1. data delete bulk
2. data export bulk
3. data import bulk
4. data query
5. data update bulk
6. data upset bulk
These commands already run asynchronously by default.
[@W-17774659@ ](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000029IIaZYAW/view)

W-17774659: deprecate --async flag on async-by-default commands
